language: ruby
rvm:
  - 2.4
sudo: required
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
notifications:
  webhooks: https://discordapp.com/api/webhooks/422835991871488001/dWTE5QCVmEOgb__ay7L7-DjH5iwzmijOsf9d2C5SsmtYYy0Mfy9cnYjF_HyaqXIRkf7W